resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: default
  timelimiter:
    configs:
      default: 
        timeout-duration: 1s
    instances:
      items:
        base-config: default